services:
  app:
    image: public.ecr.aws/${DEV_ECR_REGISTRY_ALIAS}/distribute/dev:latest
    container_name: distribute-container
    restart: always
    ports:
      - "80:8080"
      - "9292:9292"
    volumes:
      - ./logs/all:/logs/all  # ALL_LOG 파일 경로 마운트
      - ./logs/warn:/logs/warn  # WARN_LOG 파일 경로 마운트
      - ./logs/error:/logs/error  # ERROR_LOG 파일 경로 마운트
    #      - ./promtail/promtail-config.yml:/app/promtail-config.yml
    networks:
      - my_network
    environment:
      - DEV_ECR_REGISTRY_ALIAS=${DEV_ECR_REGISTRY_ALIAS}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-data:/var/lib/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-provisioning:/etc/grafana/provisioning

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    restart: always
    ports:
      - '9080:9080'
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs/all:/var/logs/all
      - ./logs/warn:/var/logs/warn
      - ./logs/error:/var/logs/error
    command:
      - -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - my_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - '--config.file=/etc/loki/loki-config.yml'
      - '--config.expand-env=true'
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    restart: always
    networks:
      - my_network

networks:
  my_network: # 네트워크 정의
    driver: bridge

volumes:
  grafana-data:
    external: true
  grafana-provisioning:
    external: true
