services:
  app:
    image: public.ecr.aws/${DEV_ECR_REGISTRY_ALIAS}/distribute/dev:latest
    container_name: distribute-container
    ports:
      - "80:8080"
    env_file:
      - .env
    environment:
      - DEV_ECR_REGISTRY_ALIAS=${DEV_ECR_REGISTRY_ALIAS}
