services:
  mju-insurance-read-local:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mju-insurance
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
