services:
  app:
    image: public.ecr.aws/${DEV_ECR_REGISTRY_ALIAS}/distribute/dev:latest
    container_name: distribute-container
    ports:
      - "80:8080"
      - "9292:9292"
    networks:
      - my_network
    environment:
      - DEV_ECR_REGISTRY_ALIAS=${DEV_ECR_REGISTRY_ALIAS}


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #      - ./prometheus/prometheus-volume:/prometheus
    ports:
      - '9090:9090'
    networks:
      - my_network
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
networks:
  my_network: # 네트워크 정의
    driver: bridge
#  airdnb-prometheus:
#    image: prom/prometheus
#    container_name: prometheus-container
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일 경로
#    ports:
#      - "9090:9090"  # Prometheus UI
#    depends_on:
#      - app  # app 서비스가 실행된 후에 시작
#  airdnb-local-grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"