spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    source:
      jdbc-url: ${DB_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
    replica:
      jdbc-url: ${READ_DB_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
