server:
  port: 8080
  tomcat:
    connection-timeout: 60s
    mbeanregistry:
      enabled: true

spring:
  profiles:
    active: ${ACTIVE_NAME}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket-name: ${S3_BUCKET_NAME}
    stack:
      auto: false


jwt:
  secret-key: ${JWT_SECRET_KEY}


management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus