global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rule.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]    # 14라인

  - job_name: "spring-actuator"          # 수집하는 이름으로 임의의 이름
    metrics_path: '/actuator/prometheus' # 수집할 경로를 지정
    scrape_interval: 15s
    static_configs:
      #      - targets: [ '3.39.206.214:9292' ]      # 수집할 서버의 IP, PORT 를 지정, application.yml 에 포트를 9292로 지정했음
      - targets: [ 'distribute-container:9292' ]